
package pl.playmobile.channel.utils;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-09-25T13:57:04.064+02:00
 * Generated source version: 2.7.17
 * 
 */
public final class QueueMessagePortType_Default_Client {

    private static final QName SERVICE_NAME = new QName("http://playmobile.pl/channel/utils", "queueMessage-1");

    private QueueMessagePortType_Default_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QueueMessage1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL("http://10.10.33.51:8040/queuemessage?wsdl");
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueueMessage1 ss = new QueueMessage1(wsdlURL, SERVICE_NAME);
        QueueMessagePortType port = ss.getDefault();  
        BindingProvider bindingProvider = (BindingProvider) port;
        bindingProvider.getRequestContext().put(
              BindingProvider.ENDPOINT_ADDRESS_PROPERTY,
              "http://localhost:7994/queuemessage");
       
        
        
        
        {
        System.out.println("Invoking queueMessage...");
        pl.project4.utils.QueueMessage _queueMessage_queueMessage = new pl.project4.utils.QueueMessage();
        _queueMessage_queueMessage.setType("H");
        _queueMessage_queueMessage.setTitle("Title-2120228112");
        _queueMessage_queueMessage.setContent("Content2071880039");
        _queueMessage_queueMessage.setInlines("Inlines-1365803079");
        _queueMessage_queueMessage.setAddressTo("rafal.tyszewski@play.pl");
        _queueMessage_queueMessage.setAddressFrom("rafal.tyszewski@play.pl");
        _queueMessage_queueMessage.setSystemName("SystemName-737211648");
        _queueMessage_queueMessage.setSystemUserName("SystemUserName1189594724");
        _queueMessage_queueMessage.setSystemId("SystemId-306135295");
        try {
            port.queueMessage(_queueMessage_queueMessage);

        } catch (ServiceFault e) { 
            System.out.println("Expected exception: ServiceFault has occurred.");
            System.out.println(e.toString());
        }
            }
 

        System.exit(0);
    }

}
