
package pl.playmobile.channel.utils;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-09-25T13:57:04.116+02:00
 * Generated source version: 2.7.17
 */

@WebFault(name = "ServiceFault", targetNamespace = "http://esb.p4.org")
public class ServiceFault extends Exception {
    
    private org.p4.esb.ServiceFault serviceFault;

    public ServiceFault() {
        super();
    }
    
    public ServiceFault(String message) {
        super(message);
    }
    
    public ServiceFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceFault(String message, org.p4.esb.ServiceFault serviceFault) {
        super(message);
        this.serviceFault = serviceFault;
    }

    public ServiceFault(String message, org.p4.esb.ServiceFault serviceFault, Throwable cause) {
        super(message, cause);
        this.serviceFault = serviceFault;
    }

    public org.p4.esb.ServiceFault getFaultInfo() {
        return this.serviceFault;
    }
}
